import streamlit as st
import pandas as p


options_for_answers = [
'1. Cela est complètement faux pour moi.',
'2. Le plus souvent faux pour moi.',
'3. Plutôt vrai que faux pour moi.',
'4. Assez vrai pour moi.',
'5. Le plus souvent vrai pour moi.',
'6. Me décrit parfaitement.']

@st.cache
def get_questions():
    with open("./young-questions.txt", 'r') as fp:
        lines = fp.readlines()
    category = "1st_category"
    result_list = []
    for line in lines:
        line = line.strip()
        if len(line)<5:
            continue
        elif line[:2]=="*(":
            category = line.strip()
        elif line[0].isnumeric(): # if a ligne starts with a number the it should be a question
            if line.count('.')==0:
                continue
            question_number = line.split(".")[0]
            question_text = line[line.index(".")+1:].strip() #" ".join(line.split(".")[1:]).strip()
            
            result_list.append(
                (category,
                question_number,
                 question_text
                )
            )
    return result_list

st.title("Questionnaire des schémas de pensée")

#result_list = get_questions()
#st.write(str(result_list))

result_list = [('*(ed)', '1', "Les autres n'ont pas satisfait mes besoins affectifs."),
 ('*(ed)', '2', "Je n'ai pas reçu suffisamment d'amour et d'attention."),
 ('*(ed)',
  '3',
  "Dans l'ensemble, je n'ai eu personne sur qui compter pour recevoir des conseils ou du soutien affectif."),
 ('*(ed)',
  '4',
  "La plupart du temps, je n'ai eu personne pour m'aider à grandir, pour partager son univers intérieur avec moi, ou qui se soucie profondément de tout ce qui m'arrive."),
 ('*(ed)',
  '5',
  "Pour la plus grande partie de ma vie, je n'ai eu personne qui veuille être près de moi et passer beaucoup de temps avec moi."),
 ('*(ed)',
  '6',
  "En général, les autres n'ont pas été présents pour me prendre dans leurs bras, pour me donner de la chaleur et de l'affection."),
 ('*(ed)',
  '7',
  "Pour la plus grande partie de ma vie, je n'ai jamais eu le sentiment que je représentais quelqu'un d'important pour quelqu'un d'autre."),
 ('*(ed)',
  '8',
  "En grande partie, je n'ai eu personne qui m'écoute réellement, me comprenne et soit sensible à mes besoins et mes sentiments véritables."),
 ('*(ed)',
  '9',
  "J'ai rarement eu une personne forte pour me donner de bons conseils ou pour me guider lorsque je ne savais pas quoi faire."),
 ('*(ab)',
  '10',
  "Je suis préoccupé(e) par le fait que les gens que j'aime vont mourir bientôt même s'il y a peu de raisons médicales à ma préoccupation"),
 ('*(ab)',
  '11',
  "Je m'accroche aux gens dont je suis proche par peur qu'ils ne me quittent."),
 ('*(ab)',
  '12',
  "Je crains que les gens dont je me sens proche ne me quittent ou ne m'abandonnent."),
 ('*(ab)',
  '13',
  "J'ai le sentiment de manquer d'une base stable qui me soutienne affectivement."),
 ('*(ab)',
  '14',
  "Je n'ai pas l'impression que les relations importantes dureront : je m'attends à ce qu'elles finissent."),
 ('*(ab)',
  '15',
  "Je me sens «accro» aux partenaires qui ne peuvent pas s'engager avec moi de façon stable."),
 ('*(ab)', '16', 'Je finirai seul(e).'),
 ('*(ab)',
  '17',
  "Quand je sens que quelqu'un à qui je tiens s'éloigne de moi, je deviens désespéré(e)."),
 ('*(ab)',
  '18',
  "Quelquefois j'ai tellement peur que les gens m'abandonnent que je les repousse."),
 ('*(ab)',
  '19',
  "Je deviens bouleversé(e) quand quelqu'un me laisse seul(e) même pour une courte période."),
 ('*(ab)',
  '20',
  'Je ne peux compter sur la présence régulière de ceux qui me soutiennent.'),
 ('*(ab)',
  '21',
  "Je ne peux me permettre d'être vraiment proche des autres car je ne peux être sûr(e) qu'ils seront toujours là."),
 ('*(ab)',
  '22',
  'Il me semble que les personnes importantes dans ma vie sont toujours en train de venir et de repartir.'),
 ('*(ab)',
  '23',
  "J'ai très peur que les personnes que j'aime ne trouvent quelqu'un d'autre qu'elles préfèrent et qu'elles m'abandonnent."),
 ('*(ab)',
  '24',
  'Les gens qui me sont proches ont toujours été très imprévisibles : un moment ils sont disponibles et gentils, puis, ils sont fâchés, contrariés, querelleurs, préoccupés par eux mêmes...'),
 ('*(ab)',
  '25',
  "J'ai tellement besoin des autres que j'ai peur de les perdre."),
 ('*(ab)',
  '26',
  'Je ne peux être moi-même ou exprimer ce que je ressens véritablement, sinon les autres vont me quitter.'),
 ('*(ma)', '27', "J'ai l'impression que les autres vont profiter de moi."),
 ('*(ma)',
  '28',
  "J'ai souvent l'impression que je dois me protéger des autres."),
 ('*(ma)',
  '29',
  "J'ai l'impression que je dois être sur mes gardes en présence des autres sinon ils me blesseront intentionnellement."),
 ('*(ma)',
  '30',
  "Si une personne est aimable avec moi, je suppose qu'elle cherche à obtenir quelque chose."),
 ('*(ma)',
  '31',
  "Ce n'est qu'une question de temps avant que quelqu'un me trahisse."),
 ('*(ma)', '32', 'La plupart des gens pensent uniquement à eux.'),
 ('*(ma)',
  '33',
  "J'ai la plus grande difficulté à faire confiance aux autres."),
 ('*(ma)', '34', 'Je suis très méfiant(e) quant aux motivations des autres.'),
 ('*(ma)',
  '35',
  "Les autres sont rarement honnêtes, ils ne sont pas en général ce qu'ils paraissent."),
 ('*(ma)',
  '36',
  "Je m'interroge habituellement sur les véritables intentions des autres."),
 ('*(ma)',
  '37',
  "Si je pense que quelqu'un cherche à me blesser, je cherche à le blesser en premier."),
 ('*(ma)',
  '38',
  'Les autres habituellement doivent faire leurs preuves avant que je leur accorde ma confiance.'),
 ('*(ma)',
  '39',
  "Je teste les autres pour voir s'ils me disent la vérité ou s'ils sont bien intentionnés."),
 ('*(ma)',
  '40',
  'Je souscris à la croyance : «Contrôle ou tu seras contrôlé(e).»'),
 ('*(ma)',
  '41',
  "Je me mets en colère quand je pense aux façons dont j'ai été maltraité(e)par les autres tout au long de ma vie."),
 ('*(ma)',
  '42',
  "Tout au long de ma vie, mes proches ont profité de moi et m'ont utilise(e) à leurs propres desseins."),
 ('*(ma)',
  '43',
  "J'ai été physiquement. émotionnellement, ou sexuellement abusé(e) par des personnes importantes de ma vie."),
 ('*(ma)', '44', 'Je ne suis pas adapté(e).'),
 ('*(ma)', '45', 'Je suis fondamentalement différent(e) des autres.'),
 ('*(ma)', '46', 'Je suis à part; je suis un(e) solitaire.'),
 ('*(ma)', '47', 'Je me sens étranger(ère) aux autres.'),
 ('*(ma)', '48', 'Je me sens isolé(e) et seul(e).'),
 ('*(ma)', '49', "Je me sens toujours à l'extérieur des groupes."),
 ('*(ma)', '50', 'Personne ne me comprend vraiment.'),
 ('*(ma)', '51', 'Ma famille a toujours été différente des autres familles.'),
 ('*(ma)', '52', "J'ai parfois le sentiment d'être un étranger."),
 ('*(ma)', '53', 'Si je disparaissais demain, personne ne le remarquerait.'),
 ('*(ds)',
  '54',
  "Aucun homme ou femme que je désire ne pourrait m'aimer une fois qu'il(elle) aurait vu mes défauts."),
 ('*(ds)',
  '55',
  'Aucune personne que je désire ne pourrait rester proche de moi si elle savait qui je suis réellement.'),
 ('*(ds)',
  '56',
  'Je suis fondamentalement imparfait(e) et rnarqué(e) par un défaut.'),
 ('*(ds)',
  '57',
  "Même si je me donne le plus grand mal, je sens qu'il ne sera pas possible d'obtenir le respect d'un homme ou d'une femme important(e) et de sentir que j'ai de la valeur."),
 ('*(ds)',
  '58',
  "Je ne mérite pas l'amour, l'attention et le respect des autres."),
 ('*(ds)',
  '59',
  "J'ai le sentiment d'être quelqu'un que l'on ne peut pas aimer."),
 ('*(ds)',
  '60',
  'Je suis trop fondamentalement inacceptable pour me révéler aux autres.'),
 ('*(ds)',
  '61',
  "Je ne pourrais pas affronter les gens, s'ils découvraient mes défauts fondamentaux."),
 ('*(ds)',
  '62',
  "Lorsque les gens m'apprécient. j'ai l'impression de les duper."),
 ('*(ds)',
  '63',
  'Je suis souvent attiré(e) par les gens qui sont très critiques envers moi ou qui me rejettent.'),
 ('*(ds)',
  '64',
  "J'ai des secrets que je ne veux pas que mes proches découvrent."),
 ('*(ds)',
  '65',
  "C'est de ma faute si mes parents n'ont pas pu m'aimer suffisamment."),
 ('*(ds)',
  '66',
  'Je ne laisse pas les gens connaître ce que je suis réellement.'),
 ('*(ds)',
  '67',
  'Une de mes plus grandes peurs est que mes défauts deviennent publics.'),
 ('*(ds)',
  '68',
  "Je ne puis comprendre comment qui que ce soit pourrait m'aimer."),
 ('*(ds)',
  '69',
  "Presque rien de ce que je fais au travail (ou à l'école) n'est aussi bon que ce que font les autres."),
 ('*(ds)', '70', "Je suis incompétent(e) quand il s'agit de réussir."),
 ('*(ds)',
  '71',
  "La plupart des gens sont plus doués que moi en ce qui concerne le travail (ou l'école) et la réussite."),
 ('*(ds)', '72', 'Je suis un(e) raté(e).'),
 ('*(ds)',
  '73',
  "Je n'ai pas autant de talent que les autres au travail (ou à l'école)."),
 ('*(ds)',
  '74',
  "Je ne suis pas aussi intelligent (e) que la plupart des gens quand il s'agit du travail (ou de l'école)."),
 ('*(ds)',
  '75',
  "Je suis humilié(e) par mes échecs ou mes insuffisances dans le monde du travail (ou de l'école)."),
 ('*(ds)',
  '76',
  "Je suis souvent mal à l'aise avec les autres car je ne les vaux pas en termes de réussites."),
 ('*(ds)',
  '77',
  "Je compare souvent mes réalisations à celles des autres et je trouve qu'ils réussissent beaucoup mieux."),
 ('*(di)',
  '78',
  'Je ne me sens pas capable de me débrouiller par moi-même dans la vie de tous les jours.'),
 ('*(di)', '79', "J'ai besoin des autres pour m'aider à m'en sortir."),
 ('*(di)',
  '80',
  "Je n'ai pas le sentiment que je puisse bien m'adapter par moi-même."),
 ('*(di)',
  '81',
  'Je crois que les autres peuvent prendre soin de moi mieux que je ne le peux moi-même.'),
 ('*(di)',
  '82',
  "J'ai des difficultés à prendre en charge de nouvelles tâches en dehors du travail à moins que quelqu'un ne me guide."),
 ('*(di)',
  '83',
  'Je me considère comme une personne dépendante en ce qui concerne la vie de tous les jours.'),
 ('*(di)',
  '84',
  "Je bousille tout ce que j'entreprends, même à l'extérieur du travail (ou de l'école)."),
 ('*(di)', '85', 'Je suis stupide dans la plupart des domaines de la vie.'),
 ('*(di)',
  '86',
  'Si je me fie à mon jugement dans la vie de tous les jours, je vais prendre la mauvaise décision.'),
 ('*(di)', '87', 'Je manque de bon sens.'),
 ('*(di)',
  '88',
  'On ne peut se fier à mon jugement dans les situations quotidiennes.'),
 ('*(di)',
  '89',
  "Je n'ai pas confiance dans ma capacité à résoudre les problèmes qui se posent tous les jours."),
 ('*(di)',
  '90',
  "Je pense avoir besoin de quelqu'un sur qui je puisse compter pour me donner des conseils sur les questions pratiques."),
 ('*(di)',
  '91',
  "Je me sens plus un(e) enfant qu'un(e) adulte quand il s'agit de prendre en main les responsabilités quotidiennes."),
 ('*(di)',
  '92',
  'Je me sens dépassé(e) par les responsabilités de tous les jours.'),
 ('*(vu)',
  '93',
  "Il ne me semble pas possible d'échapper au sentiment que quelque chose de mauvais va bientôt se passer."),
 ('*(vu)',
  '94',
  "J'ai l'impression qu'un désastre naturel, criminel, financier ou médical pourrait frapper à tout moment."),
 ('*(vu)',
  '95',
  "J'ai peur de devenir un(e) sans domicile fixe ou un (e) mendiant(e)."),
 ('*(vu)', '96', "J'ai peur d'être attaqué(e)."),
 ('*(vu)',
  '97',
  "Je prends de grandes précautions pour éviter de tomber malade ou d'être blessé(e)."),
 ('*(vu)',
  '98',
  "J'ai peur d'avoir une maladie grave, même si rien de sérieux n'a été diagnostiqué par un médecin."),
 ('*(vu)', '99', "Je suis quelqu'un de peureux(se)."),
 ('*(vu)',
  '100',
  'Je me soucie beaucoup de ce qui va mal dans le monde : le crime, la pollution, etc.'),
 ('*(vu)',
  '101',
  "J'ai souvent le sentiment que je pourrais devenir fou (folle)."),
 ('*(vu)',
  '102',
  "J'ai souvent l'impression que je vais avoir une crise d'angoisse."),
 ('*(vu)',
  '103',
  "J'ai souvent peur d'avoir une crise cardiaque ou un cancer, même s'il y a peu de raisons médicales de s'en soucier."),
 ('*(vu)', '104', 'Je pense que le monde est un endroit dangereux.'),
 ('*(eu)',
  '105',
  "Je n'ai pas pu me séparer de ma mère ou de mon pbre comme semblent le faire les gens de mon âge."),
 ('*(eu)',
  '106',
  'Mes parents et moi avons tendance à être sur-impliqués dans nos vies et nos problèmes réciproques.'),
 ('*(eu)',
  '107',
  'Il est très difficile, pour mes parents et moi-même, de garder secrets. chacun pour soi, certains détails intimes, sans nous sentir trahis ou coupables.'),
 ('*(eu)',
  '108',
  "Mes parents et moi devons nous parler presque tous les jours, sinon l'un de nous se sent coupable, blessé(e), déçu (e), ou seul (e)."),
 ('*(eu)',
  '109',
  "J'ai souvent l'impression de ne pas avoir une identité distincte de celle de mes parents ou de mon partenaire."),
 ('*(eu)',
  '110',
  "J'ai souvent l'impression que mes parents vivent à travers moi je n'ai pas une vie qui me soit propre."),
 ('*(eu)',
  '111',
  "Il m'est vraiment ardu de maintenir une distance vis-à-vis des gens dont je suis intime; il m'est difficile de me sentir une personne séparée."),
 ('*(eu)',
  '112',
  'Je suis tellement lié(e) à mon partenaire ou à mes parents que je ne sais pas vraiment qui je suis ou ce que je veux.'),
 ('*(eu)',
  '113',
  "J'éprouve des difficultés à distinguer mon point de vue ou mon opinion de ceux de mes parents ou de mon partenaire."),
 ('*(eu)',
  '114',
  "J'ai souvent l'impression de ne pas avoir d'intimité par rapport à mes parents ou mon partenaire."),
 ('*(eu)',
  '115',
  "Je sens que mes parents seraient vraiment peinés si je vivais seul(e), loin d'eux."),
 ('*(sb)',
  '116',
  "Je laisse les autres faire ce qu'ils veulent, car j'ai peur des conséquences."),
 ('*(sb)',
  '117',
  'Je pense que si je fais ce que je veux, je cours après les problèmes.'),
 ('*(sb)',
  '118',
  "Je sens que je n'ai pas d'autre choix que de me soumettre aux souhaits des autres, sinon ils exerceront des représailles ou me rejetteront d'une façon ou d'une autre."),
 ('*(sb)',
  '119',
  "Dans mes relations, je laisse l'autre avoir le dessus sur moi."),
 ('*(sb)',
  '120',
  'Je laisse toujours les autres choisir à ma place, si bien que je ne sais pas vraiment ce que je veux moi-même.'),
 ('*(sb)',
  '121',
  "J'ai le sentiment que les décisions importantes de ma vie n'étaient pas vraiment les miennes."),
 ('*(sb)',
  '122',
  "Je me soucie beaucoup de plaire aux autres. pour qu'ils ne me rejettent pas."),
 ('*(sb)',
  '123',
  "J'ai beaucoup de difficultés à exiger que mes droits soient respectés et que mes sentiments soient pris en compte."),
 ('*(sb)',
  '124',
  'Plutôt que manifester ouvertement ma colère, je me venge dans des petites choses.'),
 ('*(sb)',
  '125',
  "Je vais tolérer beaucoup plus de choses que la plupart des gens afin d'éviter une confrontation."),
 ('*(ss)',
  '126',
  'Je fais passer les besoins des autres avant les miens, sinon je me sens coupable.'),
 ('*(ss)',
  '127',
  'Je me sens coupable si je laisse tomber les autres ou si je les déçois.'),
 ('*(ss)', '128', 'Je donne davantage aux autres que je ne reçois en retour.'),
 ('*(ss)',
  '129',
  'Je suis celui (celle) qui finit généralement par prendre soin des gens dont je suis proche.'),
 ('*(ss)',
  '130',
  "Il n'y a presque rien que je ne puisse supporter lorsque j'aime quelqu'un."),
 ('*(ss)',
  '131',
  "Je suis quelqu'un de bon car je pense aux autres plus qu'à moi-même."),
 ('*(ss)',
  '132',
  'Au travail, je suis habituellement celui (celle) qui est volontaire pour faire des heures ou des tâches supplémentaires.'),
 ('*(ss)',
  '133',
  'Même si je suis très occupé(e), je trouve toujours du temps pour les autres.'),
 ('*(ss)',
  '134',
  "Je peux m'en sortir avec vraiment très peu car mes besoins sont minimes."),
 ('*(ss)',
  '135',
  "Je ne suis heureux(se) que si les gens qui m'entourent le sont aussi."),
 ('*(ss)',
  '13G',
  "Je suis tellement occupé(e) à me dévouer pour les gens qui m'importent que j'ai très peu de temps pour moi."),
 ('*(ss)',
  '137',
  "J'ai toujours été celui (celle) qui écoute les problèmes des autres."),
 ('*(ss)',
  '138',
  "Je me sens plus à l'aise pour donner un cadeau que pour en recevoir un."),
 ('*(ss)',
  '139',
  "On me voit comme quelqu'un qui en fait trop pour les autres et pas assez pour lui-même."),
 ('*(ss)', '140', "Peu importe combien je donne, ce n'est jamais assez."),
 ('*(ss)',
  '141',
  "Si je fais ce que je veux, je me sens vraiment. mal à l'aise."),
 ('*(ss)',
  '142',
  "Il m'est vraiment difficile de demander aux autres de se soucier de mes besoins."),
 ('*(ei)', '143', "J'ai peur de perdre le contrôle de mes actes."),
 ('*(ei)',
  '144',
  "J'ai peur de faire du mal à quelqu'un, physiquement ou affectivement. si je perds tout contrôle sur ma colère."),
 ('*(ei)',
  '145',
  'Je sens que je dois contrôler mes émotions et mes impulsions, sinon quelque chose de déplorable risque de se produire.'),
 ('*(ei)',
  '146',
  "J'en arrive à accumuler en moi beaucoup de colère et de ressentiment que je n'exprime pas."),
 ('*(ei)',
  '147',
  "Je suis trop gêné(e) pour exprimer des sentiments positifs aux autres (par ex. de l'affection, de l'intérêt)."),
 ('*(ei)',
  '148',
  "Je trouve embarrassant d'exprimer mes sentiments aux autres."),
 ('*(ei)', '149', "Il m'est difficile d'être chaleureux (se) et spontané(e)."),
 ('*(ei)',
  '150',
  "Je me contrôle tellement bien que les autres croient que je n'ai pas d'émotions."),
 ('*(ei)', '151', 'Les gens me trouvent coincé(e) sur le plan émotionnel.'),
 ('*(us)',
  '152',
  "Je dois être le (la) meilleur (e) dans presque tout ce que je fais, je ne peux pas accepter d'être le (la) deuxième."),
 ('*(us)', '153', "Je m'efforce de tout maintenir parfaitement en ordre."),
 ('*(us)',
  '154',
  'Je dois apparaître sous mon meilleur aspect la plupart du temps.'),
 ('*(us)',
  '155',
  "Je m'efforce de faire de mon mieux; je ne peux pas me contenter d'être «assez bien»."),
 ('*(us)',
  '156',
  "J'ai tant de choses à faire qu'il ne me reste presque pas de temps pour me détendre vraiment."),
 ('*(us)',
  '157',
  "Presque rien de ce que je fais n'est assez bien, je pourrais toujours faire mieux."),
 ('*(us)', '158', 'Je dois faire face à toutes mes responsabilités.'),
 ('*(us)',
  '159',
  'Je ressens une pression constante qui me force à faire les choses et à les réussir.'),
 ('*(us)',
  '160',
  "Mes relations souffrent de ce que je m'impose trop de choses."),
 ('*(us)',
  '161',
  "Je m'impose une telle pression pour bien faire que ma santé en souffre."),
 ('*(us)',
  '162',
  'Souvent je sacrifie plaisir et bonheur pour atteindre mes idéaux.'),
 ('*(us)',
  '163',
  'Lorsque je fais une erreur, je mérite une critique sévère.'),
 ('*(us)',
  '164',
  "Je ne peux pas accepter de me dégager aisément d'une situation' difficile ou de présenter des excuses pour mes erreurs."),
 ('*(us)', '165', "Je suis quelqu'un de très compétitif."),
 ('*(us)',
  '166',
  "J'attache beaucoup d'importance à l'argent ou au statut social."),
 ('*(us)',
  '167',
  "Je tiens toujours à être le (la) meilleur (e) dans ce que j'accomplis."),
 ('*(et)',
  '168',
  "Lorsque j'attends quelque chose des autres, j'ai beaucoup de difficulté à accepter un refus."),
 ('*(et)',
  '169',
  "Je me mets souvent en colère ou je m'irrite quand je rie peux pas avoir ce que je veux."),
 ('*(et)',
  '170',
  "je suis quelqu'un de spécial et je ne devrais pas avoir à accepter les restrictions auxquelles les autres doivent se soumettre."),
 ('*(et)',
  '171',
  "Je déteste être contraint(e) ou qu'on m'empêche de faire ce que je veux."),
 ('*(et)',
  '172',
  "Je crois que je n'ai pas à suivre les règles et les conventions comme les autres."),
 ('*(et)',
  '173',
  "J'ai le sentiment que j'ai beaucoup plus à offrir que les autres."),
 ('*(et)',
  '174',
  'Habituellement, je fais passer mes besoins avant ceux des autres.'),
 ('*(et)',
  '175',
  "Je remarque souvent que l'importance accordée à mes priorités personnelles ne me laisse plus de temps pour les amis ou la famille."),
 ('*(et)',
  '176',
  'Les autres me disent souvent que je contrôle trop la façon dont les choses sont faites.'),
 ('*(et)',
  '177',
  'Je suis très irrité(e) lorsque les autres ne font pas ce que je leur demande.'),
 ('*(et)',
  '178',
  'Je ne supporte pas que les autres me disent ce que je dois faire.'),
 ('*(is)',
  '179',
  "J'ai beaucoup de difficultés à m'arrêter de boire, de fumer, de trop manger ou à cesser d'autres comportements problématiques."),
 ('*(is)',
  '180',
  'Il ne me semble pas possible de me discipliner pour terminer des tâches routinières ou ennuyeuses.'),
 ('*(is)',
  '181',
  'Souvent, je me laisse aller à mes impulsions ou à exprimer des émotions qui me créent des difficultés ou blessent les autres.'),
 ('*(is)',
  '182',
  "Si je ne peux pas atteindre un but, je suis facilement frustré(e) et j'abandonne."),
 ('*(is)',
  '183',
  "11 m'est très difficile de sacrifier une gratification immédiate pour mener à bien un projet à long terme."),
 ('*(is)',
  '184',
  'Quand je me mets en colère, il est fréquent que je ne puisse pas du tout me contrôler.'),
 ('*(is)',
  '185',
  "J'ai tendance à abuser de certaines choses. même si je sais que c'est mauvais pour moi."),
 ('*(is)', '186', "Je m'ennuie très facilement."),
 ('*(is)',
  '187',
  'Quand les tâches deviennent difficiles, je ne peux souvent pas persévérer pour les terminer.'),
 ('*(is)',
  '188',
  'Je ne peux pas me concentrer longtemps sur quoi que ce soit.'),
 ('*(is)',
  '189',
  "Je ne peux pas me forcer à faire des choses qui ne me plaisent pas même quand je sais que c'est pour mon bien."),
 ('*(is)', '190', 'Je me mets en colère à la moindre offense.'),
 ('*(is)', '191', "J'ai rarement été capable de tenir mes engagements."),
 ('*(is)',
  '192',
  "Je ne peux presque jamais m'empêcher de montrer aux gens mes véritables sentiments, même si cela doit me coûter cher."),
 ('*(is)', '193', "J'agis souvent impulsivement et je le regrette plus tard."),
 ('*(as)',
  '194',
  "Il m'est important d'être aimé(e) par presque tous ceux que je connais."),
 ('*(as)',
  '195',
  "Je modifie mon comportement en fonction des gens avec qui je me trouve. afin qu'ils puissent m'aimer davantage."),
 ('*(as)', '196', "Je fais tout mon possible pour m'adapter."),
 ('*(as)',
  '197',
  'Mon estime personnelle est principalement fondée sur la façon dont les autres me voient.'),
 ('*(as)',
  '198',
  "Posséder de l'argent et connaître des gens importants sont des choses qui me donnent de la valeur."),
 ('*(as)',
  '199',
  "Je consacre beaucoup de temps à soigner mon apparence afin de gagner l'estime des autres."),
 ('*(as)',
  '200',
  'Mes réussites ont plus de valeur à mes yeux si les autres lesremarquent.'),
 ('*(as)',
  '201',
  "Je suis à ce point soucieux(e) de m'adapter aux autres qu'il m'arrive de ne plus savoir qui je suis."),
 ('*(as)',
  '202',
  'Je trouve difficile de me fixer des objectifs propres, sans prendre en compte ce que les autres vont penser de mes choix.'),
 ('*(as)',
  '203',
  "Lorsque je considère les décisions que j'ai prises dans ma vie, je réalise que la plupart d'entre elles reposaient sur le désir d'obtenir l'approbation des autres."),
 ('*(as)',
  '204',
  "Même si je n'aime pas une personne, je tiens malgré tout à ce qu'elle m'aime."),
 ('*(as)',
  '205',
  "À moins d'obtenir beaucoup d'attention des autres, je me sens peu important (e)"),
 ('*(as)',
  '206',
  "Si j'interviens lors d'une réunion ou si on me présente dans un groupe, je cherche à être reconnu (e) et admiré(e)."),
 ('*(as)',
  '207',
  "Lorsqu'on me fait beaucoup de compliments et d'éloges, je me sens une personne de valeur."),
 ('*(np)',
  '208',
  "Même lorsque tout va bien, j'ai l'impression que ce ne sera que temporaire."),
 ('*(np)',
  '209',
  "S'il se produit quelque chose de bien, j'ai peur qu'il n'arrive ensuite quelque chose de mauvais."),
 ('*(np)',
  '210',
  "On n'est jamais assez prudent; il peut toujours se produire quelque chose de mauvais."),
 ('*(np)',
  '211',
  "Même si je travaille beaucoup, j'ai peur de nie retrouver un jour sans le sou."),
 ('*(np)',
  '212',
  "J'ai peur qu'une mauvaise décision ne puisse conduire à un désastre."),
 ('*(np)',
  '213',
  "Je me tourmente souvent pour des décisions mineures, car les conséquences d'une erreur m'apparaissent tellement graves."),
 ('*(np)',
  '214',
  'Je préfère considérer que les choses ne vont pas aller comme je le veux, car ainsi je ne serai pas déçu (e) si ça se passe mal.'),
 ('*(np)',
  '215',
  "Je pense plutôt aux aspects négatifs de la vie et des évènements qu'aux côtés positifs."),
 ('*(np)', '216', "J'ai tendance à être pessimiste."),
 ('*(np)', '217', 'Mes proches considèrent que je me fais trop de soucis.'),
 ('*(np)',
  '218',
  "Si les gens s'enthousiasment trop, je me sens mal et j'éprouve le besoin de les prévenir de ce qui pourrait mal se passer."),
 ('*(pu)', '219', "Si je fais une erreur, je mérite d'être puni (e)."),
 ('*(pu)',
  '220',
  "Si je ne donne pas le meilleur de moi-même, je dois m'attendre à échouer."),
 ('*(pu)', '221', "Je n'ai aucune excuse si je fais une erreur."),
 ('*(pu)',
  '222',
  "Les gens qui ne font pas leur part de travail à fond devraient être punis d'une manière ou d'une autre."),
 ('*(pu)',
  '223',
  "La plupart du temps, je n'accepte pas les excuses des autres : ils n'ont pas pris leurs responsabilités et ils en paient les conséquences."),
 ('*(pu)',
  '225',
  'Je pense souvent à mes erreurs passées et je me mets en colère contre moi-même.'),
 ('*(pu)',
  '226',
  "Lorsque les gens font quelque chose de mal, j'ai du mal à appliquer la phrase : «Pardonnez et oubliez.»"),
 ('*(pu)',
  '227',
  "Je garde de la rancune envers les gens, même s'ils se sont excusés."),
 ('*(pu)',
  '228',
  "Je me sens énervé(e) à l'idée que quelqu'un s'est tiré trop facilement d'un mauvais pas."),
 ('*(pu)',
  '229',
  "Je me mets en colère lorsque des gens se trouvent des excuses, ou lorsqu'ils accusent les autres pour (les problèmes dont ils sont eux-mêmes responsables)."),
 ('*(pu)',
  '230',
  'Peu importe les raisons, quand je fais une erreur, je devrais en payer le prix.'),
 ('*(pu)',
  '231',
  "Je m'en veux énormément lorsque je bousille quelque chose."),
 ('*(pu)', '232', "Je suis quelqu'un de mauvais qui mérite d'être puni.")]


df = p.DataFrame(result_list, columns=["category", "question_number", "question_text"])
st.warning("""
Vous allez trouver ci-dessous des affirmations pouvant être utilisées par une personne 
pour se décrire elle-même. Nous vous prions de lire chaque affirmation et d'évaluer dans 
quelle mesure elle constitue une bonne description de vous-même. Lorsque vous hésitez, 
basez votre réponse sur ce que vous ressentez émotionnellement, et non pas sur ce que 
vous pensez rationnellement être vrai pour vous.
Selectionnez ensuite entre 1 et 6 la réponse vous décrivant le mieux.
""")

answers_dict = {}

with st.form("my_form"):
    for index, q in df.iterrows():
        st.caption(f"#{q.question_number}:")
        answers_dict[q.question_number] = st.selectbox(q.question_text, ['']+options_for_answers)

    run  = st.form_submit_button("Calculer le résultat")

    if run:
        df.loc[:, "answer"] = df.question_number.map(answers_dict)
        df.loc[df.answer=='', "answer"] = "0.Not answered"
        df.loc[:,"answer_short"] = df.answer.map(lambda x: "A"+x.split(".")[0])
        unanswered_questions = df.loc[df.answer.str.startswith("0.Not answered")].question_number.values
        if len(unanswered_questions)>0:
            unanswered_questions_str = ", ".join(["#"+x for x in unanswered_questions])
            st.error("Vous n'avez pas répondu aux affirmations suivantes : "+unanswered_questions_str)

        #df_analysis = df.groupby("category").answer.value_counts()
        df_analysis = df.groupby("category").answer_short.value_counts().unstack(level=0).fillna(0).T.applymap(int)
        st.subheader("Tableau des résultats:")
        st.write(df_analysis)
        results_analysis = df_analysis.to_string()
        st.session_state["results_report"] = results_analysis + f"\n\n" + "\n".join(("Q"+df.question_number+"/"+df.answer+" : "+df.question_text).values) #df[["category", "question_number", "answer_short", "question_text"]].to_string()


if 'results_report' in st.session_state:
    st.download_button('Télécharger la synthèse', st.session_state["results_report"])

